### ISSUE TITLE
Windows Installation

### ISSUE THREAD

**Issue by suneelbvs** [IanAWatson/Lilly-Medchem-Rules#18]
Hi,

Im trying to execute this in windows through cygwin. Can you please help me out in exploring this issue. Thanks in advance

![image](https://user-images.githubusercontent.com/334679/103933922-224f8a80-514a-11eb-9e31-87d446f1314b.png)

**Comment by suneelbvs** [comment]
installed ruby package, solved the issue

**Comment by IanAWatson** [comment]
Hi Suneel

Sorry for the late reply, I have been away from home.

Yes, the rules do have a ruby dependency, something that may change, but
for now, it is needed.

I hope the tool is doing what you need, I do most development on Linux, so
things like Mac and Windows do sometimes encounter difficulties.

ian
