### ISSUE TITLE
read input from stdin

### ISSUE THREAD

**Issue by flc** [IanAWatson/Lilly-Medchem-Rules#6]
It would be great if the program could read the input from standard input instead of a file just like it does with the output. It could make it possible to run it on gzipped files without extracting and writing them to disk first.
Thank you if you consider it!

**Comment by IanAWatson** [comment]
The software can already read gzip'd input - as long as the file name ends with .smi.gz or .sdf.gz
If you want to read from stdin, then you must tell it what kind of input is coming. So

```
zcat file.smi.gz | Lilly_Medchem_Rules.rb -i smi - > ok.smi
```
(note the extra '-' in the input, which is interpreted as stdin). This should work the same as
```
Lilly_Medchem_Rules.rb file.smi.gz > ok.smi
```
Let me know if this works as you need. Either way should work.

**Comment by flc** [comment]
oh, cool, it seems to work!
what I needed is something like this:
`zcat file_*.smi.gz | Lilly_Medchem_Rules.rb -i smi - | pigz -9 > ok.smi.gz`
and it works as expected, thank you!
