### ISSUE TITLE
Issues with compiling on redhat

### ISSUE THREAD

**Issue by jmoch** [IanAWatson/Lilly-Medchem-Rules#7]
Hi Ian!  I'm having issues trying to compile on redhat.  Looking through the README if I run echo 'echo $LD_LIBRARY_PATH I get no result so it appears I don't have one.  Maybe I need to create one or specify one?  From some searching this seems to be a legacy SunOS thing?  I've pasted below the output from trying to run make...

Thanks!
Jason

[jochoada@svldresource01 Lilly-Medchem-Rules-master]$ make
cd supporting_libraries && make install
make[1]: Entering directory '/opt/jochoada/bin/Lilly-Medchem-Rules-master/supporting_libraries'
g++ -O2 -I . -I ../include -Wall -ffast-math -DLINUX -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DIW_IMPLEMENTATIONS_EXPOSED -std=c+                                       +11   -c -o iwstring_data_source.o iwstring_data_source.cc
In file included from iwstring_data_source.cc:18:0:
../include/iwstring_data_source.h:7:10: fatal error: lzma.h: No such file or directory
 #include "lzma.h"
          ^~~~~~~~
compilation terminated.
make[1]: *** [<builtin>: iwstring_data_source.o] Error 1
make[1]: Leaving directory '/opt/jochoada/bin/Lilly-Medchem-Rules-master/supporting_libraries'
make: *** [Makefile:11: supporting_libraries] Error 2
[jochoada@svldresource01 Lilly-Medchem-Rules-master]$

**Comment by IanAWatson** [comment]
Hi Jason

Am at work now, so very quick..

Just try removing that line. It is an idea I ultimately did not do

Let me know...

Ian

**Comment by jmoch** [comment]
Hi Ian,
Thanks for looking :) 
I have both gcc 4.8.5 base installed
 and 7.2.1  as part of devtools-7 
I have  zlib 1.2.7 (/usr/share/doc) /and 1.2.11 /opt/local/zlib-1.2.11) not sure where the code is looking for zlib if that is a problem...

When compiling with 4.8:  Fails because no gcc-g++ installed?

[jochoada@svldresource01 Lilly-Medchem-Rules-master]$ make
cd supporting_libraries && make install
make[1]: Entering directory `/opt/jochoada/bin/Lilly-Medchem-Rules-master/supporting_libraries'
g++ -O2 -I . -I ../include -Wall -ffast-math -DLINUX -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DIW_IMPLEMENTATIONS_EXPOSED -std=c++11   -c -o iwstrin          g_data_source.o iwstring_data_source.cc
make[1]: g++: Command not found
make[1]: *** [iwstring_data_source.o] Error 127
make[1]: Leaving directory `/opt/jochoada/bin/Lilly-Medchem-Rules-master/supporting_libraries'
make: *** [supporting_libraries] Error 2

after running scl enable devtoolset-7 bash

Funny thing is lzma.h is not listed in any of the supporting_libraries that I could find with grep

[jochoada@svldresource01 Lilly-Medchem-Rules-master]$ make
cd supporting_libraries && make install
make[1]: Entering directory '/opt/jochoada/bin/Lilly-Medchem-Rules-master/supporting_libraries'
g++ -O2 -I . -I ../include -Wall -ffast-math -DLINUX -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DIW_IMPLEMENTATIONS_EXPOSED -std=c++11   -c -o iwstring_data_source.o iwstring_data_source.cc
In file included from iwstring_data_source.cc:18:0:
../include/iwstring_data_source.h:7:10: fatal error: lzma.h: No such file or directory
 #include "lzma.h"
          ^~~~~~~~
compilation terminated.
make[1]: *** [<builtin>: iwstring_data_source.o] Error 1
make[1]: Leaving directory '/opt/jochoada/bin/Lilly-Medchem-Rules-master/supporting_libraries'
make: *** [Makefile:11: supporting_libraries] Error 2

**Comment by IanAWatson** [comment]
Hi Jason

A little more relaxed.

Edit the file

include/iwstring_data_source.h

and remove the line that says #include "lzma.h"

that is an idea I was going to explore, but never actually did. I will push
that to GitHub, since there is no reason for it to be there.

There might still be some lingering issues with zlib, but first, let's get
past this first issue - perhaps zlib will be OK, but not sure.

Very happy to help, so let me know what you find. Seems the rules are being
used in a lot of different places, I often get emails from people, which is
great.

I hope things are going well. Jibo is going to release more of the Molecule
related stuff, so hopefully some of that will be useful to you as well -
although I might need to write some fingerprint related stuff...

Let me know...

Thanks

ian

**Comment by jmoch** [comment]
That was the ticket Ian!  Thanks so much for your help!!
